export enum AbilityKeyword {
	Animal = 'Animal',
	Animapathy = 'Animapathy',
	Area = 'Area',
	Charge = 'Charge',
	Chronopathy = 'Chronopathy',
	Cryokinesis = 'Cryokinesis',
	Earth = 'Earth',
	Fire = 'Fire',
	Green = 'Green',
	Magic = 'Magic',
	Melee = 'Melee',
	Metamorphosis = 'Metamorphosis',
	Persistent = 'Persistent',
	Psionic = 'Psionic',
	Pyrokinesis = 'Pyrokinesis',
	Ranged = 'Ranged',
	Resistance = 'Resistance',
	Resopathy = 'Resopathy',
	Rot = 'Rot',
	Routine = 'Routine',
	Strike = 'Strike',
	Telekinesis = 'Telekinesis',
	Telepathy = 'Telepathy',
	Void = 'Void',
	Weapon = 'Weapon'
}
