export enum FeatureType {
	Text = 'Text',
	Ability = 'Ability',
	AbilityCost = 'Ability Cost',
	Bonus = 'Bonus',
	Choice = 'Choice',
	ClassAbility = 'Class Ability',
	DamageModifier = 'Damage Modifier',
	Domain = 'Domain',
	DomainFeature = 'Domain Feature',
	Kit = 'Kit',
	KitType = 'Kit Type',
	Language = 'Language',
	LanguageChoice = 'Language Choice',
	Malice = 'Malice',
	Multiple = 'Multiple Features',
	Perk = 'Perk',
	Size = 'Size',
	Skill = 'Skill',
	SkillChoice = 'Skill Choice',
	Speed = 'Speed',
	TitleChoice = 'Title'
}
