name: Build and deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      label:
        description: 'Image label'
        required: true

env:
  CONTAINER_REGISTRY: ${{ vars.DOCR_REGISTRY || 'registry.digitalocean.com/forgesteel' }}
  IMAGE_NAME: ${{ vars.DOCR_IMAGE_NAME || 'forgesteel-app' }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    
      - name: Log in to DOCR with short-lived credentials
        run: doctl registry login --expiry-seconds 600
      
      - name: Set image tag if run manually
        if: "${{ inputs.label != '' }}"
        run: echo "IMAGE_TAG=$INPUT_LABEL" >> $GITHUB_ENV
        env:
          INPUT_LABEL: ${{ inputs.label }}
  
      - name: Set image tag to commit hash if run from a push
        if: "${{ inputs.label == '' }}"
        run: echo "IMAGE_TAG=$(echo $GITHUB_SHA | head -c7)" >> $GITHUB_ENV

      - name: Set full image name
        run: echo "FULL_IMAGE_NAME=${CONTAINER_REGISTRY}/${IMAGE_NAME}" >> $GITHUB_ENV

      - name: Check image name
        run: echo "${{ env.FULL_IMAGE_NAME }}:${{ env.IMAGE_TAG }}"

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.FULL_IMAGE_NAME }}:${{ env.IMAGE_TAG }},${{ env.FULL_IMAGE_NAME }}:latest
